/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as EffectivenessRouteImport } from './routes/effectiveness'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as ProposalsIndexRouteImport } from './routes/proposals.index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as ProposalsIdRouteImport } from './routes/proposals.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectivenessRoute = EffectivenessRouteImport.update({
  id: '/effectiveness',
  path: '/effectiveness',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIndexRoute = ProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIdRoute = ProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/effectiveness': typeof EffectivenessRoute
  '/patterns': typeof PatternsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/effectiveness': typeof EffectivenessRoute
  '/patterns': typeof PatternsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/proposals': typeof ProposalsIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/effectiveness': typeof EffectivenessRoute
  '/patterns': typeof PatternsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/effectiveness'
    | '/patterns'
    | '/runs'
    | '/settings'
    | '/proposals/$id'
    | '/sessions/$id'
    | '/proposals/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/effectiveness'
    | '/patterns'
    | '/runs'
    | '/settings'
    | '/proposals/$id'
    | '/sessions/$id'
    | '/proposals'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/effectiveness'
    | '/patterns'
    | '/runs'
    | '/settings'
    | '/proposals/$id'
    | '/sessions/$id'
    | '/proposals/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  EffectivenessRoute: typeof EffectivenessRoute
  PatternsRoute: typeof PatternsRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  ProposalsIdRoute: typeof ProposalsIdRoute
  SessionsIdRoute: typeof SessionsIdRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effectiveness': {
      id: '/effectiveness'
      path: '/effectiveness'
      fullPath: '/effectiveness'
      preLoaderRoute: typeof EffectivenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof ProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$id': {
      id: '/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof ProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  EffectivenessRoute: EffectivenessRoute,
  PatternsRoute: PatternsRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  ProposalsIdRoute: ProposalsIdRoute,
  SessionsIdRoute: SessionsIdRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
